import { ListingFeatureCategory } from '../types';

export const LISTING_FEATURE_CATEGORY_LABELS: Record<
  ListingFeatureCategory,
  string
> = {
  safety: 'Безопасност',
  comfort: 'Комфорт',
  other: 'Други',
  exterior: 'Екстериор',
  protection: 'Защита',
  interior: 'Интериор',
  specialized: 'Специализирани',
};

export const LISTING_FEATURE_CATEGORIES: ListingFeatureCategory[] = [
  'safety',
  'comfort',
  'other',
  'exterior',
  'protection',
  'interior',
  'specialized',
];

export const LISTING_FEATURE_OPTIONS: {
  key: string;
  category: ListingFeatureCategory;
  label: string;
  sortOrder: number;
}[] = [
  {
    key: 'gps_tracking',
    category: 'safety',
    label: 'GPS система за проследяване',
    sortOrder: 10,
  },
  {
    key: 'adaptive_front_lights',
    category: 'safety',
    label: 'Адаптивни предни светлини',
    sortOrder: 20,
  },
  {
    key: 'abs',
    category: 'safety',
    label: 'Антиблокираща система',
    sortOrder: 30,
  },
  {
    key: 'rear_airbags',
    category: 'safety',
    label: 'Въздушни възглавници - Задни',
    sortOrder: 40,
  },
  {
    key: 'front_airbags',
    category: 'safety',
    label: 'Въздушни възглавници - Предни',
    sortOrder: 50,
  },
  {
    key: 'side_airbags',
    category: 'safety',
    label: 'Въздушни възглавници - Странични',
    sortOrder: 60,
  },
  {
    key: 'ebd',
    category: 'safety',
    label: 'Ел. разпределяне на спирачното усилие',
    sortOrder: 70,
  },
  {
    key: 'esp',
    category: 'safety',
    label: 'Електронна програма за стабилизиране',
    sortOrder: 80,
  },
  {
    key: 'tpms',
    category: 'safety',
    label: 'Контрол на налягането на гумите',
    sortOrder: 90,
  },
  {
    key: 'parking_sensors',
    category: 'safety',
    label: 'Парктроник',
    sortOrder: 100,
  },
  {
    key: 'isofix',
    category: 'safety',
    label: 'Система ISOFIX',
    sortOrder: 110,
  },
  {
    key: 'dynamic_stability',
    category: 'safety',
    label: 'Система за динамична устойчивост',
    sortOrder: 120,
  },
  {
    key: 'traction_control',
    category: 'safety',
    label: 'Система за защита от пробуксуване',
    sortOrder: 130,
  },
  {
    key: 'distance_control',
    category: 'safety',
    label: 'Система за контрол на дистанцията',
    sortOrder: 140,
  },
  {
    key: 'hill_descent_control',
    category: 'safety',
    label: 'Система за контрол на спускането',
    sortOrder: 150,
  },

  {
    key: 'camera_360_or_rear',
    category: 'comfort',
    label: '360 camera \\ Задна камера',
    sortOrder: 1010,
  },
  {
    key: 'apple_carplay_android_auto',
    category: 'comfort',
    label: 'Apple CarPlay \\ Android Auto',
    sortOrder: 1020,
  },
  {
    key: 'auto_start_stop',
    category: 'comfort',
    label: 'Auto Start Stop function',
    sortOrder: 1030,
  },
  {
    key: 'bluetooth_handsfree',
    category: 'comfort',
    label: 'Bluetooth \\ handsfree система',
    sortOrder: 1040,
  },
  { key: 'dvd_tv', category: 'comfort', label: 'DVD, TV', sortOrder: 1050 },
  {
    key: 'head_up_display',
    category: 'comfort',
    label: 'Head up display',
    sortOrder: 1060,
  },
  {
    key: 'steptronic_tiptronic',
    category: 'comfort',
    label: 'Steptronic, Tiptronic',
    sortOrder: 1070,
  },
  {
    key: 'usb_aux',
    category: 'comfort',
    label: 'USB, audio\\video, IN\\AUX изводи',
    sortOrder: 1080,
  },
  {
    key: 'automatic_trunk',
    category: 'comfort',
    label: 'Автоматично затваряне на багажника',
    sortOrder: 1090,
  },
  {
    key: 'adaptive_air_suspension',
    category: 'comfort',
    label: 'Адаптивно въздушно окачване',
    sortOrder: 1100,
  },
  {
    key: 'keyless_start',
    category: 'comfort',
    label: 'Безключово палене',
    sortOrder: 1110,
  },
  {
    key: 'differential_lock',
    category: 'comfort',
    label: 'Блокаж на диференциала',
    sortOrder: 1120,
  },
  {
    key: 'onboard_computer',
    category: 'comfort',
    label: 'Бордкомпютър',
    sortOrder: 1130,
  },
  {
    key: 'low_high_gears',
    category: 'comfort',
    label: 'Бързи \\ бавни скорости',
    sortOrder: 1140,
  },
  {
    key: 'seat_ventilation',
    category: 'comfort',
    label: 'Вентилация на седалките',
    sortOrder: 1150,
  },
  {
    key: 'light_sensor',
    category: 'comfort',
    label: 'Датчик за светлина',
    sortOrder: 1160,
  },
  {
    key: 'electric_mirrors',
    category: 'comfort',
    label: 'Ел. Огледала',
    sortOrder: 1170,
  },
  {
    key: 'electric_windows',
    category: 'comfort',
    label: 'Ел. Стъкла',
    sortOrder: 1180,
  },
  {
    key: 'electric_seats',
    category: 'comfort',
    label: 'Ел. регулиране на седалките',
    sortOrder: 1190,
  },
  {
    key: 'electric_power_steering',
    category: 'comfort',
    label: 'Ел. усилвател на волана',
    sortOrder: 1200,
  },
  {
    key: 'air_conditioning',
    category: 'comfort',
    label: 'Климатик',
    sortOrder: 1210,
  },
  {
    key: 'climatronic',
    category: 'comfort',
    label: 'Климатроник',
    sortOrder: 1220,
  },
  {
    key: 'multifunction_steering_wheel',
    category: 'comfort',
    label: 'Мултифункционален волан',
    sortOrder: 1230,
  },
  {
    key: 'navigation',
    category: 'comfort',
    label: 'Навигация',
    sortOrder: 1240,
  },
  {
    key: 'heated_steering_wheel',
    category: 'comfort',
    label: 'Отопление на волана',
    sortOrder: 1250,
  },
  {
    key: 'auxiliary_heater',
    category: 'comfort',
    label: 'Печка',
    sortOrder: 1260,
  },
  {
    key: 'heated_windshield',
    category: 'comfort',
    label: 'Подгряване на предното стъкло',
    sortOrder: 1270,
  },
  {
    key: 'heated_seats',
    category: 'comfort',
    label: 'Подгряване на седалките',
    sortOrder: 1280,
  },
  {
    key: 'adjustable_steering_wheel',
    category: 'comfort',
    label: 'Регулиране на волана',
    sortOrder: 1290,
  },
  {
    key: 'rain_sensor',
    category: 'comfort',
    label: 'Сензор за дъжд',
    sortOrder: 1300,
  },
  {
    key: 'power_steering',
    category: 'comfort',
    label: 'Серво усилвател на волана',
    sortOrder: 1310,
  },
  {
    key: 'headlight_washers',
    category: 'comfort',
    label: 'Система за измиване на фаровете',
    sortOrder: 1320,
  },
  {
    key: 'cruise_control',
    category: 'comfort',
    label: 'Система за контрол на скоростта (автопилот)',
    sortOrder: 1330,
  },
  {
    key: 'heat_pump',
    category: 'comfort',
    label: 'Термопомпа',
    sortOrder: 1340,
  },
  {
    key: 'cooled_glovebox',
    category: 'comfort',
    label: 'Хладилна жабка',
    sortOrder: 1350,
  },

  { key: 'four_wheel_drive', category: 'other', label: '4x4', sortOrder: 2010 },
  { key: 'seven_seats', category: 'other', label: '7 места', sortOrder: 2020 },
  { key: 'buy_back', category: 'other', label: 'Buy back', sortOrder: 2030 },
  { key: 'barter', category: 'other', label: 'Бартер', sortOrder: 2040 },
  {
    key: 'lpg_system',
    category: 'other',
    label: 'Газова уредба',
    sortOrder: 2050,
  },
  { key: 'long_base', category: 'other', label: 'Дълга база', sortOrder: 2060 },
  {
    key: 'reserved_or_sold',
    category: 'other',
    label: 'Капариран\\Продаден',
    sortOrder: 2070,
  },
  {
    key: 'crashed',
    category: 'other',
    label: 'Катастрофирал',
    sortOrder: 2080,
  },
  { key: 'short_base', category: 'other', label: 'Къса база', sortOrder: 2090 },
  { key: 'leasing', category: 'other', label: 'Лизинг', sortOrder: 2100 },
  {
    key: 'cng_system',
    category: 'other',
    label: 'Метанова уредба',
    sortOrder: 2110,
  },
  { key: 'for_parts', category: 'other', label: 'На части', sortOrder: 2120 },
  {
    key: 'fully_serviced',
    category: 'other',
    label: 'Напълно обслужен',
    sortOrder: 2130,
  },
  { key: 'new_import', category: 'other', label: 'Нов внос', sortOrder: 2140 },
  {
    key: 'registered',
    category: 'other',
    label: 'С регистрация',
    sortOrder: 2150,
  },
  {
    key: 'service_book',
    category: 'other',
    label: 'Сервизна книжка',
    sortOrder: 2160,
  },
  { key: 'tuning', category: 'other', label: 'Тунинг', sortOrder: 2170 },

  {
    key: 'two_three_doors',
    category: 'exterior',
    label: '2(3) Врати',
    sortOrder: 3010,
  },
  {
    key: 'four_five_doors',
    category: 'exterior',
    label: '4(5) Врати',
    sortOrder: 3020,
  },
  {
    key: 'led_headlights',
    category: 'exterior',
    label: 'LED фарове',
    sortOrder: 3030,
  },
  {
    key: 'xenon_headlights',
    category: 'exterior',
    label: 'Ксенонови фарове',
    sortOrder: 3040,
  },
  {
    key: 'alloy_wheels',
    category: 'exterior',
    label: 'Лети джанти',
    sortOrder: 3050,
  },
  {
    key: 'metallic_paint',
    category: 'exterior',
    label: 'Металик',
    sortOrder: 3060,
  },
  {
    key: 'panoramic_roof',
    category: 'exterior',
    label: 'Панорамен люк',
    sortOrder: 3070,
  },
  {
    key: 'roof_rails',
    category: 'exterior',
    label: 'Рейлинг на покрива',
    sortOrder: 3080,
  },
  { key: 'spoilers', category: 'exterior', label: 'Спойлери', sortOrder: 3090 },
  { key: 'tow_hook', category: 'exterior', label: 'Теглич', sortOrder: 3100 },
  {
    key: 'halogen_headlights',
    category: 'exterior',
    label: 'Халогенни фарове',
    sortOrder: 3110,
  },
  { key: 'sunroof', category: 'exterior', label: 'Шибедах', sortOrder: 3120 },

  {
    key: 'offroad_package',
    category: 'protection',
    label: 'OFFROAD пакет',
    sortOrder: 4010,
  },
  { key: 'alarm', category: 'protection', label: 'Аларма', sortOrder: 4020 },
  {
    key: 'armored',
    category: 'protection',
    label: 'Брониран',
    sortOrder: 4030,
  },
  { key: 'casco', category: 'protection', label: 'Каско', sortOrder: 4040 },
  { key: 'winch', category: 'protection', label: 'Лебедка', sortOrder: 4050 },
  {
    key: 'central_locking',
    category: 'protection',
    label: 'Централно заключване',
    sortOrder: 4060,
  },

  {
    key: 'velour_interior',
    category: 'interior',
    label: 'Велурен салон',
    sortOrder: 5010,
  },
  {
    key: 'right_hand_drive',
    category: 'interior',
    label: 'Десен волан',
    sortOrder: 5020,
  },
  {
    key: 'leather_interior',
    category: 'interior',
    label: 'Кожен салон',
    sortOrder: 5030,
  },
  {
    key: 'light_interior',
    category: 'interior',
    label: 'Светъл салон',
    sortOrder: 5040,
  },

  { key: 'taxi', category: 'specialized', label: 'TAXI', sortOrder: 6010 },
  {
    key: 'disabled_access',
    category: 'specialized',
    label: 'За хора с увреждания',
    sortOrder: 6020,
  },
  {
    key: 'hearse',
    category: 'specialized',
    label: 'Катафалка',
    sortOrder: 6030,
  },
  {
    key: 'ambulance',
    category: 'specialized',
    label: 'Линейка',
    sortOrder: 6040,
  },
  {
    key: 'training_vehicle',
    category: 'specialized',
    label: 'Учебен',
    sortOrder: 6050,
  },
  {
    key: 'refrigerated',
    category: 'specialized',
    label: 'Хладилен',
    sortOrder: 6060,
  },
  {
    key: 'homologation_n1',
    category: 'specialized',
    label: 'Хомологация N1',
    sortOrder: 6070,
  },
];
